# SQLite version 3.x
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'sqlite3'
#
default: &default
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  adapter: sqlite3
  timeout: 5000
  database: db/development.sqlite3

test:
  <<: *default
  adapter: sqlite3
  timeout: 5000
  database: db/test.sqlite3

production:
  <<: *default
  adapter: postgresql
  encoding: unicode
  database: myapp_production
  username: myapp
  password: <%= ENV['MYAPP_DATABASE_PASSWORD'] %>