# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a70fcf4d8cf4a1a8eaa169741679c69768baabfe529e21a3f31c7ea787f869942af4d7245c3a3588d904f9e162a3fe011dc7be1382e748d71b9f48f38cdb4d4b
  intercom_app_id: xcsif1wh
  intercom_app_secret: OrHMJ36ACnG6P0hJ4RdycHNpjC8fs2Wk5MD0S1KB
  intercom_access_token: dG9rOmY2NmUyZjQxXzYxODlfNGZjOV9hYzY5XzM4ZDM0ZWMwODlmZToxOjA=

staging:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  intercom_app_id: <%= ENV["INTERCOM_APP_ID"] %>
  intercom_app_secret: <%= ENV["INTERCOM_APP_SECRET"] %>
  intercom_access_token: <%= ENV["INTERCOM_ACCESS_TOKEN"] %>

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  intercom_app_id: <%= ENV["INTERCOM_APP_ID"] %>
  intercom_app_secret: <%= ENV["INTERCOM_APP_SECRET"] %>
  intercom_access_token: <%= ENV["INTERCOM_ACCESS_TOKEN"] %>
